In [1]:
import os
os.getcwd()

'd:\\SRK\\Projects\\ML\\TVH-ZH\\Documents\\ath\\data'

In [1]:
# Pass it as clean, vertical raw text. 
# This completely stops linters from freezing up.
raw_symbols_text = """
360ONE 3MINDIA AADHARHFC AARTIDRUGS AARTIIND AARTIPHARM AAVAS ABB ABBOTINDIA ABCAPITAL ABDL ABFRL ABLBL ABREL ABSLAMC ACC ACE ACI ACMESOLAR ACUTAAS ADANIENSOL ADANIENT ADANIGREEN ADANIPORTS ADANIPOWER ADVENZYMES AEGISLOG AEGISVOPAK AEQUS AETHER AFCONS AFFLE AGARWALEYE AHLUCONT AIAENG AIIL AJANTPHARM AKUMS ALIVUS ALKEM ALKYLAMINE ALOKINDS AMBER AMBUJACEM ANANDRATHI ANANTRAJ ANGELONE ANTHEM ANUP ANURAS APARINDS APLAPOLLO APLLTD APOLLO APOLLOHOSP APOLLOTYRE APTUS ARE&M ARVIND ARVINDFASN ASAHIINDIA ASHAPURMIN ASHOKA ASHOKLEY ASIANPAINT ASKAUTOLTD ASTERDM ASTRAL ASTRAMICRO ATGL ATHERENERG ATLANTAELE ATUL AUBANK AURIONPRO AUROPHARMA AVALON AVANTIFEED AVL AWFIS AWL AXISBANK AXISCADES AZAD BAJAJ-AUTO BAJAJELEC BAJAJFINSV BAJAJHFL BAJAJHLDNG BAJFINANCE BALAMINES BALKRISIND BALRAMCHIN BALUFORGE BANCOINDIA BANDHANBNK BANKBARODA BANKINDIA BATAINDIA BAYERCROP BBOX BBTC BDL BECTORFOOD BEL BELRISE BEML BERGEPAINT BHARATFORG BHARTIARTL BHARTIHEXA BHEL BIKAJI BIOCON BIRLACORPN BLACKBUCK BLS BLUEDART BLUEJET BLUESTARCO BLUESTONE BORORENEW BOSCHLTD BPCL BRIGADE BRITANNIA BSE BSOFT CAMPUS CAMS CANBK CANFINHOME CANHLIFE CAPILLARY CAPLIPOINT CARBORUNIV CARTRADE CASTROLIND CCAVENUE CCL CDSL CEATLTD CELLO CEMPRO CENTRALBK CENTURYPLY CERA CESC CGCL CGPOWER CHALET CHAMBLFERT CHENNPETRO CHOICEIN CHOLAFIN CHOLAHLDNG CIEINDIA CIPLA CLEAN CMSINFO COALINDIA COCHINSHIP COFORGE COHANCE COLPAL CONCOR CONCORDBIO COROMANDEL CORONA CPPLUS CRAFTSMAN CRAMC CREDITACC CRISIL CRIZAC CROMPTON CSBBANK CUB CUMMINSIND CUPID CYIENT DABUR DALBHARAT DATAMATICS DATAPATTNS DBL DBREALTY DCBBANK DCMSHRIRAM DEEPAKFERT DEEPAKNTR DELHIVERY DEVYANI DIACABS DIVISLAB DIXON DLF DMART DOMS DRREDDY DYNAMATECH ECLERX EDELWEISS EICHERMOT EIDPARRY EIEL EIHOTEL ELECON ELECTCAST ELGIEQUIP ELLEN EMAMILTD EMBDL EMCURE EMIL EMMVEE ENDURANCE ENGINERSIN ENRIN ENTERO EPL EQUITASBNK ERIS ESCORTS ETERNAL ETHOSLTD EUREKAFORB EXIDEIND FACT FEDERALBNK FEDFINA FIEMIND FINCABLES FINPIPE FIRSTCRY FIVESTAR FLUOROCHEM FORCEMOT FORTIS FSL GABRIEL GAEL GAIL GALLANTT GESHIP GHCL GICRE GILLETTE GLAND GLAXO GLENMARK GMDCLTD GMMPFAUDLR GMRAIRPORT GMRP&UI GNFC GODFRYPHLP GODIGIT GODREJAGRO GODREJCP GODREJIND GODREJPROP GOKEX GOKULAGRO GPIL GPPL GRANULES GRAPHITE GRASIM GRAVITA GREAVESCOT GROWW GRSE GRWRHITECH GSFC GVT&D HAL HAPPSTMNDS HAVELLS HBLENGINE HCC HCG HCLTECH HDBFS HDFCAMC HDFCBANK HDFCLIFE HEG HEMIPROP HERITGFOOD HEROMOTOCO HEXT HFCL HGINFRA HINDALCO HINDCOPPER HINDPETRO HINDUNILVR HINDZINC HOMEFIRST HONASA HONAUT HSCL HUDCO HYUNDAI ICICIAMC ICICIBANK ICICIGI ICICIPRULI ICIL IDBI IDEA IDFCFIRSTB IEX IFBIND IFCI IGIL IGL IIFL IIFLCAPS IKS IMFA INDGN INDHOTEL INDIACEM INDIAGLYCO INDIAMART INDIANB INDIASHLTR INDIGO INDIGOPNTS INDUSINDBK INDUSTOWER INFY INOXGREEN INOXINDIA INOXWIND INTELLECT IOB IOC IONEXCHANG IPCALAB IRB IRCON IRCTC IREDA IRFC ITC ITCHOTELS ITI IXIGO J&KBANK JAIBALAJI JAINREC JAMNAAUTO JAYNECOIND JBCHEPHARM JBMA JINDALSAW JINDALSTEL JIOFIN JKCEMENT JKLAKSHMI JKPAPER JKTYRE JLHL JMFINANCIL JPPOWER JSFB JSL JSLL JSWCEMENT JSWDULUX JSWENERGY JSWINFRA JSWSTEEL JUBLFOOD JUBLINGREA JUBLPHARMA JUSTDIAL JWL JYOTHYLAB JYOTICNC KAJARIACER KALYANKJIL KANSAINER KARURVYSYA KAYNES KEC KEI KFINTECH KIMS KIRLOSBROS KIRLOSENG KIRLPNU KITEX KNRCON KOTAKBANK KPIGREEN KPIL KPITTECH KPRMILL KRBL KRN KSB KSCL KTKBANK LALPATHLAB LATENTVIEW LAURUSLABS LEMONTREE LENSKART LGEINDIA LICHSGFIN LICI LINDEINDIA LLOYDSENGG LLOYDSENT LLOYDSME LODHA LOTUSDEV LT LTF LTFOODS LTM LTTS LUMAXTECH LUPIN LXCHEM M&M M&MFIN MAHABANK MAHSCOOTER MAHSEAMLES MANAPPURAM MANKIND MANORAMA MANYAVAR MAPMYINDIA MARICO MARKSANS MARUTI MASTEK MAXHEALTH MAZDOCK MCX MEDANTA MEDPLUS MEESHO METROPOLIS MFSL MGL MIDHANI MINDACORP MMTC MOIL MOTHERSON MOTILALOFS MPHASIS MRF MRPL MSTCLTD MSUMI MTARTECH MUTHOOTFIN NAM-INDIA NATCOPHARM NATIONALUM NAUKRI NAVA NAVINFLUOR NAZARA NBCC NCC NEOGEN NESCO NESTLEIND NETWEB NETWORK18 NEULANDLAB NEWGEN NFL NH NHPC NIACL NIVABUPA NLCINDIA NMDC NSLNISP NTPC NTPCGREEN NUVAMA NUVOCO NYKAA OBEROIRLTY OFSS OIL OLAELEC OLECTRA ONESOURCE ONGC OPTIEMUS ORIENTCEM ORKLAINDIA OSWALPUMPS PAGEIND PARADEEP PARAS PARKHOSPS PATANJALI PAYTM PCBL PCJEWELLER PERSISTENT PETRONET PFC PFIZER PFOCUS PGEL PGIL PHOENIXLTD PICCADIL PIDILITIND PIIND PINELABS PIRAMALFIN PNB PNBHOUSING PNCINFRA PNGJL POLICYBZR POLYCAB POLYMED POONAWALLA POWERGRID POWERINDIA POWERMECH PPLPHARMA PRAJIND PREMIERENE PRESTIGE PRICOLLTD PRIVISCL PRSMJOHNSN PRUDENT PTC PTCIL PURVA PVRINOX PWL QPOWER QUESS RADICO RAILTEL RAIN RAINBOW RALLIS RAMCOCEM RATEGAIN RATNAMANI RAYMONDLSL RBA RBLBANK RCF RECLTD REDINGTON REDTAPE REFEX RELAXO RELIANCE RELIGARE RENUKA RHIM RITES RKFORGE ROUTE RPOWER RRKABEL RTNINDIA RTNPOWER RUBICON RVNL SAATVIKGL SAFARI SAGILITY SAIL SAILIFE SAMHI SAMMAANCAP SANDUMA SANOFICONR SANSERA SAPPHIRE SARDAEN SAREGAMA SBFC SBICARD SBILIFE SBIN SCHAEFFLER SCHNEIDER SCI SENCO SFL SHAILY SHAKTIPUMP SHARDACROP SHAREINDIA SHILPAMED SHREECEM SHRIPISTON SHRIRAMFIN SHYAMMETL SIEMENS SIGNATURE SJVN SKFINDIA SKFINDUS SKIPPER SKYGOLD SMARTWORKS SMLMAH SOBHA SOLARINDS SONACOMS SONATSOFTW SOUTHBANK SPARC SPLPETRO SRF STAR STARCEMENT STARHEALTH STLTECH STYL STYRENIX SUBROS SUDARSCHEM SUDEEPPHRM SUMICHEM SUNDARMFIN SUNPHARMA SUNTECK SUNTV SUPREMEIND SUPRIYA SURYAROSNI SUZLON SWANCORP SWIGGY SWSOLAR SYNGENE SYRMA TANLA TARC TARIL TATACAP TATACHEM TATACOMM TATACONSUM TATAELXSI TATAINVEST TATAPOWER TATASTEEL TATATECH TBOTEK TCS TDPOWERSYS TECHM TECHNOE TEGA TEJASNET TENNIND TEXRAIL THANGAMAYL THELEELA THERMAX THOMASCOOK THYROCARE TI TIINDIA TIMETECHNO TIMKEN TIPSMUSIC TITAGARH TITAN TMB TMCV TMPV TORNTPHARM TORNTPOWER TRANSRAILL TRAVELFOOD TRENT TRIDENT TRITURBINE TRIVENI TSFINV TTML TVSMOTOR TVSSCS UBL UCOBANK UJJIVANSFB ULTRACEMCO UNIONBANK UNITDSPR UNOMINDA UPL URBANCO USHAMART UTIAMC UTLSOLAR V2RETAIL VAIBHAVGBL VARROC VBL VEDL VGUARD VIJAYA VIKRAMSOLR VIPIND VIYASH VMART VMM VOLTAMP VOLTAS VTL WAAREEENER WAAREERTL WABAG WAKEFIT WEBELSOLAR WELCORP WELENT WELSPUNLIV WESTLIFE WEWORK WHIRLPOOL WIPRO WOCKPHARMA YATHARTH YESBANK ZAGGLE ZEEL ZENSARTECH ZENTEC ZFCVINDIA ZYDUSLIFE ZYDUSWELL
"""

# This cleanly converts the space/newline separated text into your symbols array instantly
symbols = [s.strip().replace("'", "").replace(",", "") for s in raw_symbols_text.split() if s.strip()]

print(f"List allocated instantly. Count: {len(symbols)}")

List allocated instantly. Count: 750

In [ ]:
import os
import time
import yfinance as yf

def download_and_save_to_csv(symbols_list):
    print(f"Starting data download for {len(symbols_list)} symbols using native curl_cffi wrapper...\n")
    counter = 0
    for symbol in symbols_list:
        raw_symbol = symbol.strip().upper()
        counter += 1
        # if os.path.exists(f"{raw_symbol}.csv"):
        #     print(f"{counter}/{len(symbols_list)}. File for {raw_symbol} already exists. Skipping download.")
        #     continue
        
        if not raw_symbol.endswith('.NS') and '.' not in raw_symbol:
            ticker = f"{raw_symbol}.NS"
        else:
            ticker = raw_symbol

        print(f"{counter}/{len(symbols_list)}. Fetchingdata for: {ticker}...")
        
        try:
            df = yf.download(
                tickers=ticker,
                period="max",
                interval="1d",
                auto_adjust=False,  
                threads=False,     
                timeout=15,
                progress=False
            )
            
            if df is not None and not df.empty:
                # --- FIX: FLATTEN MULTI-INDEX COLUMNS IMMEDIATELY ---
                # If the headers look like ('Close', 'HDFCBANK.NS'), drop the ticker name layer
                if isinstance(df.columns, range) or hasattr(df.columns, 'levels') or isinstance(df.columns, yf.multi.MultiIndex) or df.columns.nlevels > 1:
                    df.columns = df.columns.get_level_values(0)
                
                # Ensure columns are completely flat string indexes
                df.columns = [str(col).strip() for col in df.columns]
                
                # Now safely drop holiday rows where 'Close' values don't exist
                if 'Close' in df.columns:
                    df = df.dropna(subset=['Close'])
                else:
                    # Fallback check if the column tracking structure is named slightly differently
                    print(f" -> Warning: 'Close' column not found in headers: {list(df.columns)}")
                
                # Define save location using the user's initial tracking input name
                filename = f"{raw_symbol}.csv"
                
                # Save data frame to disk
                df.to_csv(filename)
                print(f" -> Successfully saved: {os.path.abspath(filename)}")
            else:
                print(f" -> Warning: No data returned for {ticker}")
                
        except Exception as e:
            print(f" -> Error downloading {ticker}: {str(e)}")
            
        # Pacing window to maintain healthy API call streams across 500 records
        time.sleep(0.3)
        print("-" * 50)

In [40]:
if __name__ == "__main__":
    # List your symbols here (can be with or without '.NS')
    STOCK_SYMBOLS = symbols#["HDFCBANK", "MAHABANK", "RELIANCE", "TCS"]
    download_and_save_to_csv(STOCK_SYMBOLS)

Starting data download for 750 symbols using native curl_cffi wrapper...

1/750. Fetchingdata for: 360ONE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\360ONE.csv
--------------------------------------------------
2/750. Fetchingdata for: 3MINDIA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\3MINDIA.csv
--------------------------------------------------
3/750. Fetchingdata for: AADHARHFC.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AADHARHFC.csv
--------------------------------------------------
4/750. Fetchingdata for: AARTIDRUGS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AARTIDRUGS.csv
--------------------------------------------------
5/750. Fetchingdata for: AARTIIND.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AARTIIND.csv
--------------------------------------------------
6/750. Fetchingdata for: AARTIPHARM.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AARTIPHARM.csv
--------------------------------------------------
7/750. Fetchingdata for: AAVAS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AAVAS.csv
--------------------------------------------------
8/750. Fetchingdata for: ABB.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABB.csv
--------------------------------------------------
9/750. Fetchingdata for: ABBOTINDIA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABBOTINDIA.csv
--------------------------------------------------
10/750. Fetchingdata for: ABCAPITAL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABCAPITAL.csv
--------------------------------------------------
11/750. Fetchingdata for: ABDL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABDL.csv
--------------------------------------------------
12/750. Fetchingdata for: ABFRL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABFRL.csv
--------------------------------------------------
13/750. Fetchingdata for: ABLBL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABLBL.csv
--------------------------------------------------
14/750. Fetchingdata for: ABREL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABREL.csv
--------------------------------------------------
15/750. Fetchingdata for: ABSLAMC.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ABSLAMC.csv
--------------------------------------------------
16/750. Fetchingdata for: ACC.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ACC.csv
--------------------------------------------------
17/750. Fetchingdata for: ACE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ACE.csv
--------------------------------------------------
18/750. Fetchingdata for: ACI.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ACI.csv
--------------------------------------------------
19/750. Fetchingdata for: ACMESOLAR.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ACMESOLAR.csv
--------------------------------------------------
20/750. Fetchingdata for: ACUTAAS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ACUTAAS.csv
--------------------------------------------------
21/750. Fetchingdata for: ADANIENSOL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ADANIENSOL.csv
--------------------------------------------------
22/750. Fetchingdata for: ADANIENT.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ADANIENT.csv
--------------------------------------------------
23/750. Fetchingdata for: ADANIGREEN.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ADANIGREEN.csv
--------------------------------------------------
24/750. Fetchingdata for: ADANIPORTS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ADANIPORTS.csv
--------------------------------------------------
25/750. Fetchingdata for: ADANIPOWER.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ADANIPOWER.csv
--------------------------------------------------
26/750. Fetchingdata for: ADVENZYMES.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ADVENZYMES.csv
--------------------------------------------------
27/750. Fetchingdata for: AEGISLOG.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AEGISLOG.csv
--------------------------------------------------
28/750. Fetchingdata for: AEGISVOPAK.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AEGISVOPAK.csv
--------------------------------------------------
29/750. Fetchingdata for: AEQUS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AEQUS.csv
--------------------------------------------------
30/750. Fetchingdata for: AETHER.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AETHER.csv
--------------------------------------------------
31/750. Fetchingdata for: AFCONS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AFCONS.csv
--------------------------------------------------
32/750. Fetchingdata for: AFFLE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AFFLE.csv
--------------------------------------------------
33/750. Fetchingdata for: AGARWALEYE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AGARWALEYE.csv
--------------------------------------------------
34/750. Fetchingdata for: AHLUCONT.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AHLUCONT.csv
--------------------------------------------------
35/750. Fetchingdata for: AIAENG.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AIAENG.csv
--------------------------------------------------
36/750. Fetchingdata for: AIIL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AIIL.csv
--------------------------------------------------
37/750. Fetchingdata for: AJANTPHARM.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AJANTPHARM.csv
--------------------------------------------------
38/750. Fetchingdata for: AKUMS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AKUMS.csv
--------------------------------------------------
39/750. Fetchingdata for: ALIVUS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ALIVUS.csv
--------------------------------------------------
40/750. Fetchingdata for: ALKEM.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ALKEM.csv
--------------------------------------------------
41/750. Fetchingdata for: ALKYLAMINE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ALKYLAMINE.csv
--------------------------------------------------
42/750. Fetchingdata for: ALOKINDS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ALOKINDS.csv
--------------------------------------------------
43/750. Fetchingdata for: AMBER.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AMBER.csv
--------------------------------------------------
44/750. Fetchingdata for: AMBUJACEM.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AMBUJACEM.csv
--------------------------------------------------
45/750. Fetchingdata for: ANANDRATHI.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ANANDRATHI.csv
--------------------------------------------------
46/750. Fetchingdata for: ANANTRAJ.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ANANTRAJ.csv
--------------------------------------------------
47/750. Fetchingdata for: ANGELONE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ANGELONE.csv
--------------------------------------------------
48/750. Fetchingdata for: ANTHEM.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ANTHEM.csv
--------------------------------------------------
49/750. Fetchingdata for: ANUP.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ANUP.csv
--------------------------------------------------
50/750. Fetchingdata for: ANURAS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ANURAS.csv
--------------------------------------------------
51/750. Fetchingdata for: APARINDS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\APARINDS.csv
--------------------------------------------------
52/750. Fetchingdata for: APLAPOLLO.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\APLAPOLLO.csv
--------------------------------------------------
53/750. Fetchingdata for: APLLTD.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\APLLTD.csv
--------------------------------------------------
54/750. Fetchingdata for: APOLLO.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\APOLLO.csv
--------------------------------------------------
55/750. Fetchingdata for: APOLLOHOSP.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\APOLLOHOSP.csv
--------------------------------------------------
56/750. Fetchingdata for: APOLLOTYRE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\APOLLOTYRE.csv
--------------------------------------------------
57/750. Fetchingdata for: APTUS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\APTUS.csv
--------------------------------------------------
58/750. Fetchingdata for: ARE&M.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ARE&M.csv
--------------------------------------------------
59/750. Fetchingdata for: ARVIND.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ARVIND.csv
--------------------------------------------------
60/750. Fetchingdata for: ARVINDFASN.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ARVINDFASN.csv
--------------------------------------------------
61/750. Fetchingdata for: ASAHIINDIA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASAHIINDIA.csv
--------------------------------------------------
62/750. Fetchingdata for: ASHAPURMIN.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASHAPURMIN.csv
--------------------------------------------------
63/750. Fetchingdata for: ASHOKA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASHOKA.csv
--------------------------------------------------
64/750. Fetchingdata for: ASHOKLEY.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASHOKLEY.csv
--------------------------------------------------
65/750. Fetchingdata for: ASIANPAINT.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASIANPAINT.csv
--------------------------------------------------
66/750. Fetchingdata for: ASKAUTOLTD.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASKAUTOLTD.csv
--------------------------------------------------
67/750. Fetchingdata for: ASTERDM.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASTERDM.csv
--------------------------------------------------
68/750. Fetchingdata for: ASTRAL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASTRAL.csv
--------------------------------------------------
69/750. Fetchingdata for: ASTRAMICRO.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ASTRAMICRO.csv
--------------------------------------------------
70/750. Fetchingdata for: ATGL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ATGL.csv
--------------------------------------------------
71/750. Fetchingdata for: ATHERENERG.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ATHERENERG.csv
--------------------------------------------------
72/750. Fetchingdata for: ATLANTAELE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ATLANTAELE.csv
--------------------------------------------------
73/750. Fetchingdata for: ATUL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\ATUL.csv
--------------------------------------------------
74/750. Fetchingdata for: AUBANK.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AUBANK.csv
--------------------------------------------------
75/750. Fetchingdata for: AURIONPRO.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AURIONPRO.csv
--------------------------------------------------
76/750. Fetchingdata for: AUROPHARMA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AUROPHARMA.csv
--------------------------------------------------
77/750. Fetchingdata for: AVALON.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AVALON.csv
--------------------------------------------------
78/750. Fetchingdata for: AVANTIFEED.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AVANTIFEED.csv
--------------------------------------------------
79/750. Fetchingdata for: AVL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AVL.csv
--------------------------------------------------
80/750. Fetchingdata for: AWFIS.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AWFIS.csv
--------------------------------------------------
81/750. Fetchingdata for: AWL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AWL.csv
--------------------------------------------------
82/750. Fetchingdata for: AXISBANK.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AXISBANK.csv
--------------------------------------------------
83/750. Fetchingdata for: AXISCADES.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AXISCADES.csv
--------------------------------------------------
84/750. Fetchingdata for: AZAD.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\AZAD.csv
--------------------------------------------------
85/750. Fetchingdata for: BAJAJ-AUTO.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BAJAJ-AUTO.csv
--------------------------------------------------
86/750. Fetchingdata for: BAJAJELEC.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BAJAJELEC.csv
--------------------------------------------------
87/750. Fetchingdata for: BAJAJFINSV.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BAJAJFINSV.csv
--------------------------------------------------
88/750. Fetchingdata for: BAJAJHFL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BAJAJHFL.csv
--------------------------------------------------
89/750. Fetchingdata for: BAJAJHLDNG.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BAJAJHLDNG.csv
--------------------------------------------------
90/750. Fetchingdata for: BAJFINANCE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BAJFINANCE.csv
--------------------------------------------------
91/750. Fetchingdata for: BALAMINES.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BALAMINES.csv
--------------------------------------------------
92/750. Fetchingdata for: BALKRISIND.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BALKRISIND.csv
--------------------------------------------------
93/750. Fetchingdata for: BALRAMCHIN.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BALRAMCHIN.csv
--------------------------------------------------
94/750. Fetchingdata for: BALUFORGE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BALUFORGE.csv
--------------------------------------------------
95/750. Fetchingdata for: BANCOINDIA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BANCOINDIA.csv
--------------------------------------------------
96/750. Fetchingdata for: BANDHANBNK.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BANDHANBNK.csv
--------------------------------------------------
97/750. Fetchingdata for: BANKBARODA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BANKBARODA.csv
--------------------------------------------------
98/750. Fetchingdata for: BANKINDIA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BANKINDIA.csv
--------------------------------------------------
99/750. Fetchingdata for: BATAINDIA.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BATAINDIA.csv
--------------------------------------------------
100/750. Fetchingdata for: BAYERCROP.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BAYERCROP.csv
--------------------------------------------------
101/750. Fetchingdata for: BBOX.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BBOX.csv
--------------------------------------------------
102/750. Fetchingdata for: BBTC.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BBTC.csv
--------------------------------------------------
103/750. Fetchingdata for: BDL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BDL.csv
--------------------------------------------------
104/750. Fetchingdata for: BECTORFOOD.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BECTORFOOD.csv
--------------------------------------------------
105/750. Fetchingdata for: BEL.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BEL.csv
--------------------------------------------------
106/750. Fetchingdata for: BELRISE.NS...
 -> Successfully saved: d:\SRK\Projects\ML\TVH-ZH\Documents\ath\stock-scanner\data\BELRISE.csv
--------------------------------------------------
107/750. Fetchingdata for: BEML.NS...

In [4]:
import os

file_path = "HDFCBANK.csv"

if os.path.exists(file_path):
    print("File exists! Ready to load.")
else:
    print("File not found.")

File exists! Ready to load.

In [36]:
import yfinance as yf   
df = yf.download(
                tickers="MAHABANK.NS",
                period="3mo",
                interval="1d",
                auto_adjust=False,  # Perfect High/Close ratios 
                threads=False,     # Linear thread-safe tracking loops
                timeout=15
            )

[*********************100%***********************]  1 of 1 completed

In [37]:
df.columns = df.columns.get_level_values(0)
df.columns = [str(col).strip() for col in df.columns]
df.tail(30)

            Adj Close      Close       High        Low       Open    Volume
Date
2026-05-04  78.109016  79.300003  80.120003  78.930000  79.000000  17922648
2026-05-05  80.019875  81.239998  81.589996  78.129997  78.800003  28560769
2026-05-06  82.373978  83.629997  84.150002  82.139999  82.250000  37582297
2026-05-07  84.028748  85.309998  85.900002  83.709999  84.339996  23847379
2026-05-08  82.639931  83.900002  85.309998  82.669998  85.309998  19633062
2026-05-11  80.197174  81.419998  82.500000  79.849998  82.500000  22177064
2026-05-12  77.192986  78.370003  82.449997  78.000000  81.000000  17449726
2026-05-13  78.768951  79.970001  80.480003  78.129997  78.349998  14533430
2026-05-14  77.321030  78.500000  80.699997  77.300003  80.500000  14374430
2026-05-15  76.848236  78.019997  78.970001  77.769997  78.699997   9751597
2026-05-18  76.631546  77.800003  78.000000  76.199997  77.500000  12211000
2026-05-19  77.163429  78.339996  78.599998  77.419998  77.800003   7491904
2026-05-20  77.567276  78.750000  78.989998  77.089996  78.000000   7838024
2026-05-21  78.562103  79.760002  80.339996  79.349998  79.900002  11883310
2026-05-22  78.837898  80.040001  80.449997  79.010002  79.500000  13186459
2026-05-25  79.950928  81.169998  82.199997  80.709999  81.000000  11362497
2026-05-26  78.975800  80.180000  81.750000  79.809998  81.360001  13667175
2026-05-27  78.877296  80.080002  80.250000  79.599998  80.180000   7325388
2026-05-28  78.877296  80.080002  80.080002  80.080002  80.080002         0
2026-05-29  78.079460  79.269997  80.699997  78.400002  80.099998  11912803
2026-06-01  76.473946  77.639999  79.330002  76.900002  79.199997  14202373
2026-06-02  77.724876  78.910004  79.430000  77.070000  77.410004   9355862
2026-06-03  78.502998  79.699997  79.989998  78.040001  79.000000  11016774
2026-06-04  78.700005  79.900002  80.580002  78.839996  79.500000   8749850
2026-06-05  79.190002  79.190002  80.769997  79.000000  79.190002  12711478
2026-06-08  79.610001  79.610001  81.500000  77.800003  78.500000  15828378
2026-06-09  83.970001  83.970001  84.250000  79.599998  80.010002  37941831
2026-06-10  84.180000  84.180000  85.080002  83.410004  84.250000  19378667
2026-06-11  83.080002  83.080002  84.400002  82.830002  83.900002  13551944
2026-06-12  87.300003  87.300003  87.620003  83.669998  84.400002  36284743

In [1]:
df[:-2].max()

NameError: name 'df' is not defined

                        Close       High        Low         Open        Volume
2026-05-07	            84.028748	84.609890	82.452779	83.073315	23847379
2026-05-07	84.028748	85.309998	85.900002	83.709999	84.339996	23847379

In [85]:
import pandas as pd
df = pd.read_csv("..\\data-AdjClose_True\\MAHABANK.csv")
df.tail()

            Date      Close       High        Low       Open    Volume
5477  2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
5478  2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
5479  2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
5480  2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
5481  2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

In [48]:
df.max()

Date      2026-06-12
Close      87.300003
High       87.620003
Low        83.669998
Open       84.400002
Volume     298242980
dtype: object

In [49]:
#df[df['High'] == df['High'].max()]
df[df['Date'] == '2008-01-07']

           Date      Close       High        Low       Open  Volume
937  2008-01-07  60.710194  62.320544  59.260879  59.905019  509577

In [50]:
df.tail()

            Date      Close       High        Low       Open    Volume
5477  2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
5478  2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
5479  2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
5480  2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
5481  2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

In [ ]:
df.set_index('Date', inplace=True)
df.tail()

                Close       High        Low       Open    Volume
Date
2004-04-12  21.562887  24.604160  18.220229  18.686009  29545784
2004-04-13  21.343697  21.864275  20.823118  21.672482   8867156
2004-04-14  21.343697  21.343697  21.343697  21.343697         0
2004-04-15  21.699879  22.193059  20.987509  21.508088   7829737
2004-04-16  21.919075  22.330058  21.508092  21.891677   4824450
...               ...        ...        ...        ...       ...
2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

[5482 rows x 5 columns]

In [121]:
import yfinance as yf   
df1 = yf.download(
                tickers="MAHABANK.NS",
                period="2d",
                interval="1d",
                auto_adjust=False,  # Perfect High/Close ratios 
                threads=False,     # Linear thread-safe tracking loops
                timeout=15,
                progress=False
            )

In [122]:
df1.columns = df1.columns.get_level_values(0)
df1.columns = [str(col).strip() for col in df1.columns]
df['Date'] = pd.to_datetime(df['Date'])
df1.reset_index(inplace=True)
# df1.reset_index(drop=True)
df1.columns
df1

        Date  Adj Close      Close       High        Low       Open    Volume
0 2026-06-11  83.080002  83.080002  84.400002  82.830002  83.900002  13551944
1 2026-06-12  87.300003  87.300003  87.620003  83.669998  84.400002  36284743

In [100]:
df.tail()

           Date      Close       High        Low       Open    Volume
5476 2026-06-05  79.190002  80.769997  79.000000  79.190002  12711478
5477 2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
5478 2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
5479 2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
5480 2026-06-11  83.080002  94.400002  82.830002  83.900002  13551944

In [101]:
df1

        Date      Close       High        Low       Open    Volume
0 2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
1 2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

In [95]:
df = df[:-1]
df.tail()

            Date      Close       High        Low       Open    Volume
5476  2026-06-05  79.190002  80.769997  79.000000  79.190002  12711478
5477  2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
5478  2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
5479  2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
5480  2026-06-11  83.080002  94.400002  82.830002  83.900002  13551944

In [102]:
cdf = pd.concat([df, df1], ignore_index=True)
cdf.tail()

           Date      Close       High        Low       Open    Volume
5478 2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
5479 2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
5480 2026-06-11  83.080002  94.400002  82.830002  83.900002  13551944
5481 2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
5482 2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

In [103]:
# 3. Drop duplicate dates, keeping 'last' so df4's row overrides df3's row
df = cdf.drop_duplicates(subset=['Date'], keep='last').reset_index(drop=True)

df.tail()

           Date      Close       High        Low       Open    Volume
5477 2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
5478 2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
5479 2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
5480 2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
5481 2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

In [83]:
import pandas as pd

# 1. Recreating your DataFrames
df3 = pd.DataFrame({
    'Date': ['2026-06-05', '2026-06-08', '2026-06-09', '2026-06-10', '2026-06-11'],
    'Close': [79.190002, 79.610001, 83.970001, 84.180000, 83.080002],
    'High': [80.769997, 81.500000, 84.250000, 85.080002, 84.400002],
    'Low': [79.000000, 77.800003, 79.599998, 83.410004, 88.830002], # Note: df1 has 88.830002 here
    'Open': [79.190002, 78.500000, 80.010002, 84.250000, 83.900002],
    'Volume': [12711478, 15828378, 37941831, 19378667, 13551944]
})

df4 = pd.DataFrame({
    'Date': ['2026-06-11', '2026-06-12'],
    'Close': [83.080002, 87.300003],
    'High': [94.400002, 87.620003],
    'Low': [82.830002, 83.669998], # df2 corrects this value to 82.830002
    'Open': [83.900002, 84.400002],
    'Volume': [13551944, 36284743]
})

In [67]:
print(df3)
print(df4)

         Date      Close       High        Low       Open    Volume
0  2026-06-05  79.190002  80.769997  79.000000  79.190002  12711478
1  2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
2  2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
3  2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
4  2026-06-11  83.080002  84.400002  88.830002  83.900002  13551944
         Date      Close       High        Low       Open    Volume
0  2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
1  2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

In [68]:
# 2. Stack df4 below df3
combined = pd.concat([df3, df4], ignore_index=True)

# 3. Drop duplicate dates, keeping 'last' so df4's row overrides df3's row
df3 = combined.drop_duplicates(subset=['Date'], keep='last').reset_index(drop=True)

print(df3)

         Date      Close       High        Low       Open    Volume
0  2026-06-05  79.190002  80.769997  79.000000  79.190002  12711478
1  2026-06-08  79.610001  81.500000  77.800003  78.500000  15828378
2  2026-06-09  83.970001  84.250000  79.599998  80.010002  37941831
3  2026-06-10  84.180000  85.080002  83.410004  84.250000  19378667
4  2026-06-11  83.080002  84.400002  82.830002  83.900002  13551944
5  2026-06-12  87.300003  87.620003  83.669998  84.400002  36284743

In [105]:
df.max()

Date      2026-06-12 00:00:00
Close               87.300003
High                87.620003
Low                 83.669998
Open                84.400002
Volume              298242980
dtype: object

In [118]:
# df[df['High'] == df['High'].max()]
index_of_max_high = df['High'].idxmax()
print(index_of_max_high, df.loc[index_of_max_high]["Date"], df.loc[index_of_max_high]["High"])
while index_of_max_high > 0:
    index_of_max_high = df[0:index_of_max_high]['High'].idxmax()
    print(index_of_max_high, df.loc[index_of_max_high]["Date"], df.loc[index_of_max_high]["High"])

5481 2026-06-12 00:00:00 87.62000274658203
5479 2026-06-10 00:00:00 85.08000183105469
5455 2026-05-07 00:00:00 84.6098904005159
5454 2026-05-06 00:00:00 82.88617210965816
5444 2026-04-22 00:00:00 80.91620775793668
5443 2026-04-21 00:00:00 80.27597455333358
5411 2026-02-27 00:00:00 75.84355526917547
5410 2026-02-26 00:00:00 74.7600774015691
5409 2026-02-25 00:00:00 73.67660257827451
5408 2026-02-24 00:00:00 71.35204502487689
5407 2026-02-23 00:00:00 70.17006181230045
4977 2024-06-03 00:00:00 69.18905892207705
4972 2024-05-27 00:00:00 67.3063589383816
4955 2024-04-30 00:00:00 66.79025823312402
4954 2024-04-29 00:00:00 65.77757826666006
4902 2024-02-08 00:00:00 63.93635774674366
4901 2024-02-07 00:00:00 63.38399664480425
937 2008-01-07 00:00:00 62.320543597800665
936 2008-01-04 00:00:00 61.450941012143744
935 2008-01-03 00:00:00 60.80681390478234
934 2008-01-02 00:00:00 60.22709454229399
933 2008-01-01 00:00:00 56.65211591968679
917 2007-12-06 00:00:00 56.04017586081892
905 2007-11-20 00:00:00 55.07397287065606
904 2007-11-19 00:00:00 54.01114363433168
901 2007-11-14 00:00:00 50.6616116996392
900 2007-11-13 00:00:00 48.14945958368196
899 2007-11-12 00:00:00 45.66952691667238
896 2007-11-06 00:00:00 44.38124350426358
863 2007-09-19 00:00:00 42.41661214058812
818 2007-07-17 00:00:00 38.77722988771261
817 2007-07-16 00:00:00 36.29728915240943
812 2007-07-09 00:00:00 34.300450826526344
811 2007-07-06 00:00:00 34.13942141211868
800 2007-06-21 00:00:00 33.6240997292183
799 2007-06-20 00:00:00 33.26983252078452
788 2007-06-05 00:00:00 31.884928456942752
697 2007-01-18 00:00:00 31.628327482658374
695 2007-01-16 00:00:00 30.269301689108005
693 2007-01-12 00:00:00 29.34268671218188
691 2007-01-10 00:00:00 27.613017362760097
688 2007-01-05 00:00:00 26.006889398729545
664 2006-11-30 00:00:00 25.945118522644044
663 2006-11-29 00:00:00 25.57447283842286
661 2006-11-27 00:00:00 25.57446723645293
659 2006-11-23 00:00:00 25.48180804890432
5 2004-04-19 00:00:00 25.26172698482019
0 2004-04-12 00:00:00 24.604160237761302